name: coverage
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov=Calcclass calclass/test_calc.py --cov-report xml:.github/workflows/coverage.xml 
      - name: Get Cover 
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: .github/workflows/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}