name: 'coverage'
run-name: 'coverage'
on: [pull_request]
    
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Cover 
            uses: orgoro/coverage@v3.1
            with:
                coverageFile: .github/workflows/coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}