name: 'coverage'
run-name: 'coverage'
on: [pull_request]
    
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:

          - name: do test
            run:
              #pip install pytest-cov
              #pip install coverage
              pytest -s --cov=Calcclass ./calclass/test_calc.py --cov-report xml
              coverage xml .github/workflows/coverage.xml
          - name: Get Cover 
            uses: orgoro/coverage@v3.1
            with:
                coverageFile: path/to/coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}