name: lint
on: [pull_request]
jobs:
 lint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: psf/black@stable
     - uses: chartboost/ruff-action@v1
(calc) lluis@ll:~/prog/calcClass$ pytest -vv  ./test --cov-report 