name: test
on:
  push:
    branches:
      - main
  pull_request: {} 

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install module and dependencies
        run: python -m pip install ./
      - name: Test with pytest
        run: |
          pytest -vv --cov-config=pyproject.toml ./test --cov=mycalc
      - name: Create JSON coverage report
        run: coverage json -o coverage-summary.json
      # - name: toDel
      #   run: cat coverage.xml
      # - name: Get Cover 
      #   uses: orgoro/coverage@v3.1
      #   with:
      #     thresholdModified: 0.5
      #     thresholdAll: 0.5
      #     thresholdNew: 0.5
      #     coverageFile: coverage.xml
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: lcov-reporter
      #   uses: romeovs/lcov-reporter-action@v0.2.16
      #   with:
      #     lcov-file: ./coverage/lcov.info

      - name: Coverage Diff
        uses: greatwizard/coverage-diff-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Path of the json-summary file to analyze.

          coverage-filename: coverage-summary.json

          # Name of the json file containing the repository's default branch json-summary stored in the repo wiki.
          base-summary-filename: base-summary.json

          # If true, it will not fail even if the current branch's coverage is lower than the default branch's coverage.
          allowed-to-fail: false

          # Whether or not a badge will be generated and stored.
          badge-enabled: true

          # Name of the json file containing badge informations stored in the repo wiki.
          badge-filename: coverage-diff-badge.json

          # If the coverage percentage is above or equal to this value, the badge will be green.
          badge-threshold-green: 99

          # If the coverage percentage is not green and above or equal to this value, the badge will be orange. Otherwise it will be red.
          badge-threshold-orange: 70
