name: test
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install module and dependencies
        run: python -m pip install ./
      - name: Test with pytest
        run: |
          pytest -vv --cov-config=pyproject.toml --cov=mycalc ./test  --cov-report xml:coverage.xml 
      - name: Get Cover 
        uses: orgoro/coverage@v3.1
#        with:
#          thresholdModified: 0
#          thresholdAll: 0
#          thresholdNew: 0
#          coverageFile: coverage.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Get cover
 #       uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}