name: test
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install module and dependencies
        run: python -m pip install ./
      - name: Test with pytest
        run: |
          pytest -vv --cov=mycalc ./test --cov-report xml:coverage.xml
          coverage xml coverage.xml
      - name: Get Cover 
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
  
#jobs:
#  test:
#    name: Coverage Diff
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 16
#          cache: npm
#      - run: npm install
#      - run: npm run test
#      - name: run pytest
#        run: |
#          coverage run -m pytest 
#          coverage json
#      - name: Coverage Diff
#        uses: greatwizard/coverage-diff-action@v1.0.8
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          coverage-filename: coverage.json